worker_processes auto;
events {
    worker_connections 1024;
}

http {
    include mime.types;

    # COMPRESSING

    gzip on;
    gzip_comp_level 4;
    gzip_types      text/plain 
                    text/css 
                    application/json 
                    application/x-javascript 
                    text/xml application/xml 
                    application/xml+rss 
                    text/javascript 
                    application/javascript;


    # CACHEING

    proxy_cache_path    /var/cache/nginx 
                        levels=1:2 
                        keys_zone=my_cache:30m 
                        inactive=60s 
                        use_temp_path=off;


    server {
        listen  80;
        server_name localhost;
        root /var/mates/dist;
        index index.html;

        location = /stub_status {
            stub_status;
        }
    
        location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg)$ {
            add_header Cache-Control "public, max-age=2592000, immutable";
            add_header Pragma public;
            add_header Vary Accept-Encoding;
            expires 1M;
            access_log off;
        }
    
        location  / {
            try_files $uri $uri/ /index.html;
        }
    }
}