# Generated by Django 6.0.2 on 2026-02-05 21:18

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('profileImage', models.ImageField(blank=True, default='profileImage/Serious cat.jpeg', max_length=255, null=True, upload_to=Users.models.getProfileImageFilepath)),
                ('bio', models.CharField(blank=True, default='يوزر غلبان للتطبيق الغلبان', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField(auto_now=True)),
                ('hideEmail', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
