# Generated by Django 6.0.2 on 2026-02-12 20:12

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_account_first_name_account_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='room_banner',
            field=models.ImageField(blank=True, default='main.png', max_length=255, null=True, upload_to=Users.models.getProfileBannerFilepath),
        ),
        migrations.AlterField(
            model_name='account',
            name='profileImage',
            field=models.ImageField(blank=True, default='main.png', max_length=255, null=True, upload_to=Users.models.getProfileImageFilepath),
        ),
    ]
