# Generated by Django 5.2.11 on 2026-02-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_account_room_banner_alter_account_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
