# Generated by Django 5.2.11 on 2026-02-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='room_banner',
            new_name='profile_banner',
        ),
    ]
