# Generated by Django 5.2.11 on 2026-02-13 22:54

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_banner',
            field=models.ImageField(blank=True, default='main2.png', max_length=255, null=True, upload_to=Users.models.getProfileBannerFilepath),
        ),
    ]
