# Generated by Django 6.0.2 on 2026-02-10 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joinDate', models.DateTimeField(auto_now_add=True)),
                ('leftDate', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('member', 'Member')], default='member', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='الاخ مكسل يضيف وصف للروم او بيجرب ف مشيها يخوياو اعتبرها عشوائية او حسب الاسم بقا )موفر عليكم وقت الكتابة اهو و بضيف من عندي , عشان انا ديفيلوبر طرش جدا.', max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('study', 'Study'), ('games', 'Games'), ('programing', 'Programming'), ('life issues', 'Lifeissues'), ('other', 'Other')], default='other', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_rooms', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(through='Rooms.MemberShip', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.room'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'room'), name='unique_room_member'),
        ),
    ]
