# Generated by Django 6.0.2 on 2026-02-12 20:12

import Rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_banner',
            field=models.ImageField(blank=True, default='main.png', max_length=255, null=True, upload_to=Rooms.models.getroombannerFilepath),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, default='main.png', max_length=255, null=True, upload_to=Rooms.models.getroomImageFilepath),
        ),
    ]
